cloud:
  aws:
    s3:
      bucket: ${your_bucket_name}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${your_accessKey}
      secretKey: ${your_secretKey}

spring:
  servlet:
    multipart:
      max-file-size: 2MB