cloud:
  aws:
    s3:
      bucket: ${your_bucket_name}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${your_accessKey}
      secretKey: ${your_secretKey}